version: '2'
services:
  node:
    build: ./node
    links:
    - postgres
    environment:
    - WORDPRESS_DB_PASSWORD=password
    volumes:
    - ../:/usr/src/app
    ports:
    - "80:8080"
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=node_app
    - POSTGRES_USER=root
    ports:
    - "5432:5432"