version: '2'
services:
  node:
    build: ./node
    links:
    - postgres
    volumes:
    - ../:/usr/src/app
    ports:
    - "7100:8080"
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=node_app
    - POSTGRES_USER=root
    ports:
    - "7400:5432"
